# Generated by Django 4.1.7 on 2023-03-13 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, upload_to='manufacture/%Y/%m/%d/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='О предприятии')),
                ('code', models.CharField(max_length=16, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
                'ordering': ['-name', '-bio'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('bio', models.TextField(blank=True, verbose_name='О предприятии')),
                ('code', models.CharField(max_length=13, verbose_name='Код товара')),
                ('photo', models.ImageField(blank=True, upload_to='catalog_items/%Y/%m/%d/', verbose_name='Фото')),
                ('date_of_manufacture', models.DateField(verbose_name='Дата производства')),
                ('expiration_date', models.DateField(verbose_name='Годен до')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manufacture.manufacture', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар каталога',
                'verbose_name_plural': 'Товары каталога',
                'ordering': ['-name', '-id'],
            },
        ),
    ]
