# Generated by Django 4.1.7 on 2023-03-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
