# Generated by Django 4.1.7 on 2023-03-15 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0002_alter_manufacture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О товаре'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(252734999999999.97)], verbose_name='Цена'),
        ),
    ]
