# Generated by Django 4.1.7 on 2023-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0003_alter_catalogitem_bio_alter_catalogitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='photo',
            field=models.ImageField(upload_to='catalog_items/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='photo',
            field=models.ImageField(upload_to='manufacture/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
