# Generated by Django 4.1.7 on 2023-03-19 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0004_alter_catalogitem_photo_alter_manufacture_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='amount',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Произведено единиц'),
        ),
    ]
