# Generated by Django 4.1.7 on 2023-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0006_alter_catalogitem_date_of_manufacture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='date_of_manufacture',
            field=models.DateField(verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='expiration_date',
            field=models.DateField(verbose_name='Годен до'),
        ),
    ]
