# Generated by Django 4.1.7 on 2023-03-19 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_cartitem'),
        ('Shop', '0003_alter_shop_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDoneStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус выполнения')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('post_index', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('cart_item', models.ManyToManyField(to='Members.cartitem', verbose_name='Элемент корзины')),
                ('is_done', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.orderdonestatus', verbose_name='Статус выполнения')),
                ('profile', models.ManyToManyField(to='Members.profile', verbose_name='Пользователь')),
                ('shop', models.ManyToManyField(to='Shop.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-id'],
            },
        ),
    ]
