# Generated by Django 4.1.7 on 2023-03-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0006_profile_cart'),
        ('Shop', '0004_orderdonestatus_alter_product_amount_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Members.cartitem', verbose_name='Элемент корзины'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Members.profile', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Shop.shop', verbose_name='Магазин'),
        ),
    ]
