# Generated by Django 4.1.7 on 2023-03-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0005_catalogitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='date_of_manufacture',
            field=models.DateField(null=True, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Годен до'),
        ),
    ]
