# Generated by Django 4.1.7 on 2023-03-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0001_initial'),
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manufactures',
            field=models.ManyToManyField(blank=True, to='Manufacture.manufacture', verbose_name='Производства'),
        ),
    ]
