# Generated by Django 4.1.7 on 2023-03-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_product_stock'),
        ('Members', '0002_profile_manufactures'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shops',
            field=models.ManyToManyField(blank=True, to='Shop.shop', verbose_name='Магазины'),
        ),
    ]
