# Generated by Django 4.1.7 on 2023-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_profile_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='avatars/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
