# Generated by Django 4.1.7 on 2023-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, to='Members.cartitem', verbose_name='Корзина'),
        ),
    ]
